// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm9Uf130xb3V8ZkhPDBLg0mYkjtArYJ0Q',
    appId: '1:1039425129068:web:e66ea38e3b0765e8452649',
    messagingSenderId: '1039425129068',
    projectId: 'avengers-10d4e',
    authDomain: 'avengers-10d4e.firebaseapp.com',
    storageBucket: 'avengers-10d4e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLJQv-AoKMQo_uUxaNz7S1gpUlYyDrIeQ',
    appId: '1:1039425129068:android:73b56caf5674d1b6452649',
    messagingSenderId: '1039425129068',
    projectId: 'avengers-10d4e',
    storageBucket: 'avengers-10d4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz9TcjnH1sgE-9-sRd9TThSg7m-ClqdK8',
    appId: '1:1039425129068:ios:d07cc6b1c9e966a1452649',
    messagingSenderId: '1039425129068',
    projectId: 'avengers-10d4e',
    storageBucket: 'avengers-10d4e.appspot.com',
    iosClientId: '1039425129068-6f9jkpua6c4t6jeb8ie0je9u2dip5qip.apps.googleusercontent.com',
    iosBundleId: 'com.example.avengers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz9TcjnH1sgE-9-sRd9TThSg7m-ClqdK8',
    appId: '1:1039425129068:ios:4500aa896a8f8912452649',
    messagingSenderId: '1039425129068',
    projectId: 'avengers-10d4e',
    storageBucket: 'avengers-10d4e.appspot.com',
    iosClientId: '1039425129068-uc77te7smr3i77feadg2pfckog57sog5.apps.googleusercontent.com',
    iosBundleId: 'com.example.avengers.RunnerTests',
  );
}
